apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: spring-api
    namespace: default
    finalizers:
        - resources-finalizer.argocd.argoproj.io
    annotations:
        argocd-image-updater.argoproj.io/image-list: sousandre/spring-api
        argocd-image-updater.argoproj.io/git-branch: master
        argocd-image-updater.argoproj.io/image-list: git:secret:argocd/git-creds


    namespace: argocd
spec:
    project: default
    source:
        repoURL: https://github.com/sousa-andre/spring-boot-rest-services-with-unit-and-integration-test-config
        targetRevision: HEAD
        path: prod
    destination:
        server: https://kubernetes.default.svc
        namespace: spring
    syncPolicy:
        syncOptions:
            - CreateNamespace=true
        automated:
            selfHeal: true
            prune: true