apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node-exporter-service-monitor
  labels:
    app: node-exporter-service-monitor
    release: prometheus
  namespace: spring
spec:
  selector:
    matchLabels:
      app: node-exporter-service
  endpoints:
    - port: http-metrics
      interval: 15s