apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: cpu-alert
  namespace: prometheus
spec:
  replicas: 1
  alertmanagerConfigSelector:
    matchLabels:
      alert-manager-config: cpu-alert-config
