apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: cpu-alert-config
  namespace: prometheus
  labels:
    alert-manager-config: cpu-alert-config
spec:
  receivers:
    - name: 'webhook'
      webhookConfigs:
        - url: 'http://example.com/'

