apiVersion: apps/v1
kind: DaemonSet
metadata:
    name: node-exporter
    namespace: spring
spec:
    selector:
        matchLabels:
            name: node-exporter
    template:
        metadata:
            labels:
                name: node-exporter
        spec:
            containers:
                - name: node-exporter
                  image: quay.io/prometheus/node-exporter:latest
                  ports:
                      - containerPort: 9100