apiVersion: v1
kind: Service
metadata:
    name: spring-service
spec:
    type: LoadBalancer
    selector:
      app: spring
    ports:
        - port: 8080
          targetPort: 8080
          nodePort: 30009
