apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: registry.hub.docker.com/sousandre/spring-api
    newTag: 2.0.2
replicas:
  - name: spring
    count: 2